config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts
    root 'welcome#index'
    get 'home', :to => 'welcome#index', as: 'home'
    get 'new', :to => 'posts#new'
    get 'blog', :to => 'posts#index', as: 'blog'
    get 'members', :to => 'members#members', as: 'members'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ApplicationRecord

	extend FriendlyId
  	friendly_id :title, use: [:slugged, :history]

  	scope :most_recent, -> { order(id: :desc) }
  
  	def should_generate_new_friendly_id?
   		slug.blank? || title_changed?
  	end

  	def display_day_published
  		"Published #{created_at.strftime('%-b %-d, %-Y')}"
  	end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]

<<<<<<< HEAD
  http_basic_authenticate_with name: "ADCADMIN", password: "CHORTLE208", except: [:index, :show]
=======
  http_basic_authenticate_with name: "ADC", password: "ADC", except: [:index, :show]
>>>>>>> cfef13be2f99f4ad9f934a62d1a0d356a75139f9

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.most_recent
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :description, :banner_image_url)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<<<<<<< HEAD

<!-- Author: Arasan Kathiravan(President)
     Organization: CCSU's App Development Club -->

=======
>>>>>>> cfef13be2f99f4ad9f934a62d1a0d356a75139f9
<html>

  <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Chango" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=VT323" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lobster"/>
        <link rel="stylesheet" href="//min.gitcdn.xyz/repo/DoclerLabs/Protip/master/protip.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
<<<<<<< HEAD
        <%= favicon_link_tag 'https://s3.us-east-2.amazonaws.com/app-dev-blog-site/club_logo.ico'%>
=======
        <%= favicon_link_tag 'club_logo.ico'%>
>>>>>>> cfef13be2f99f4ad9f934a62d1a0d356a75139f9
        <title><%= yield(:page_title)%> | CCSU's App Development Club</title>
        <%= csrf_meta_tags%>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'%>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
        <script src="//min.gitcdn.xyz/repo/DoclerLabs/Protip/master/protip.min.js"></script>
    </head>

    <body>
        <!--navbar-->
        <nav class="navbar navbar-default">
            <div class="navbar-header">
                <%=link_to  home_path(@home), class: 'navbar-brand' do%> 
                App Development Club <i class="fa fa-terminal fa-lg"></i>
                <% end %>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#myNavbar" aria-expanded="false" aria-controls="navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span> 
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="myNavbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to 'Home', home_path(@home) %></li>     
                    <li><%= link_to 'Blog', blog_path(@blog) %></li>
                    <li><%= link_to 'Members', members_path(@members) %><li>
                    <li><a href="https://github.com/AppDevelopmentClub-CCSU">Projects</a></li>  
                </ul>
            </div>
        </nav>  
      <%= yield %>
    </body>

</html>

app/views/members/members.html.erb
<div class="container-fluid members-bg text-center">  
    <h1> Members </h1>
    <br/>
    <h6> Click the names of some of our members to view their LinkedIn Accounts </h6>
    <br/>

    <a href="https://www.linkedin.com/in/sebastian-arango-01635912a/"> Sebastian Arango (Treasurer)</a> <br/>
<<<<<<< HEAD
    <a href="https://www.linkedin.com/in/nilay-bhatt-3a79a7100/"> Nilay Bhatt </a> <br/>
    <a href="https://www.linkedin.com/in/asher-butler-723b10123/"> Asher Butler </a> <br/>
=======
    <a href="https://www.linkedin.com/in/asher-butler-723b10123/"> Asher Butler </a> <br/>
    <a href="https://www.linkedin.com/in/nilay-bhatt-3a79a7100/"> Nilay Bhatt </a> <br/>
>>>>>>> cfef13be2f99f4ad9f934a62d1a0d356a75139f9
    <a href="https://www.linkedin.com/in/cnoelani/"> Chelsea Edwards </a> <br/>
    <a href="https://www.linkedin.com/in/robert-gatzak-5b77b6149/"> Robert Gatzak (Vice President) </a> <br/>
    <a href="https://www.linkedin.com/in/joshua-glynn-660503126/"> Joshua Glynn (Secretary) </a> <br/>
    <a href="https://www.linkedin.com/in/robert-grospitch-b70523a9/"> Robert "RJ" Grospitch </a> <br/>
   	<a href="https://www.linkedin.com/in/robert-henley-44b35a12a/"> Robert Henley </a> <br/>
   	<a href="https://www.linkedin.com/in/justin-inho-3098b5130/"> Justin Inho </a> <br/>
    <a href="https://www.linkedin.com/in/skyler-lehan-352687126/"> Skyler Lehan (Alum Class of '17) </a> <br/>
    <a href="https://www.linkedin.com/in/arasan-kathiravan-788971129/"> Arasan Kathiravan (President) </a> <br/>
    <a href="https://www.linkedin.com/in/shelankel/"> Shelby Kelley </a> <br/>
    <a href="https://www.linkedin.com/in/deepankarmalhan/"> Deepankar Malhan </a> <br/>
<<<<<<< HEAD
    <a href="https://www.linkedin.com/in/kenneth-morton-jr-910bb4149/"> Kenneth Morton Jr </a> <br/>
    <a href="https://www.linkedin.com/in/cody-santor-380236141/"> Cody Santor </a> <br/>
    <a href="https://www.linkedin.com/in/cameron-sonido-272ba7121/"> Cameron Sonido (Alum Class of '17)</a> <br/>
    <a href="https://www.linkedin.com/in/kyle-sturmer-78861a126/"> Kyle Sturmer </a> <br/>    
    <a href="https://www.linkedin.com/in/christopher-white-5b6578ba/"> Christopher White </a> <br/>  
</div>
=======
    <a href="https://www.linkedin.com/in/cody-santor-380236141/"> Cody Santor </a> <br/>
    <a href="https://www.linkedin.com/in/cameron-sonido-272ba7121/"> Cameron Sonido (Alum Class of '17)</a> <br/>
    <a href="https://www.linkedin.com/in/kyle-sturmer-78861a126/"> Kyle Sturmer </a> <br/>    
</div>
<!--Patrick Ilinski Ken Morton Chris White <br/> <br/> <br/>-->
>>>>>>> cfef13be2f99f4ad9f934a62d1a0d356a75139f9

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

   <div class="field">
    <%= form.label :banner_image_url %>
    <%= form.text_field :banner_image_url, id: :post_banner_image_url %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.cktext_area :body, rows:10, id: :post_body %>
  </div>

  <br>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :post_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class='col-sm-6 col-lg-4'>
	<div class="card">
		<div class="card-topper" style='background-image:url(<%= post.banner_image_url %>);'>
		</div>
			<div class="card-block">
				<h4 class="card-title"><%= link_to post.title, post %></h4>
				<p class="published-date"><%= post.display_day_published %></p>
				<p class="card-text"><%= truncate(post.description, length: 130) %></p>
				<%= link_to 'Read', post, class:'btn btn-read' %>
			</div>
	</div>
</div>	

app/views/posts/edit.html.erb
<div class="container <%= controller_name %> <%= action_name %>">
	<% provide(:page_title, "Edit #@{post.title}") %>
	<br>
	<h1>Editing Post</h1>
	<%= render 'form', post: @post %>
	<%= link_to 'Show', @post %> |
	<%= link_to 'Back', posts_path %> |
	<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/posts/index.html.erb
<div class="container <%= controller_name %> <%= action_name %>">
	<% provide(:page_title, "All Posts") %>
	<br>
	<div class="row">
      <%= render @posts %> 
	</div> 
</div>

app/views/posts/new.html.erb
<div class="container <%= controller_name %> <%= action_name %>">
	<% provide(:page_title, "New Post") %>
	<br>
	<h1>New Post</h1>
	<br>
	<%= render 'form', post: @post %>
	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<% provide(:page_title, @post.title) %>

<br>

<div class="row">
<<<<<<< HEAD
	<div class="container">
		<div class="col-md-12 col-lg-12">
			<h1><center><%= @post.title %></center></h1>
			<p><center><%= @post.display_day_published %></center></p>
			<br>
			<%= raw(@post.body) %>
		</div>
=======
	<div class="col-md-12 col-lg-12">
		<h1><center><%= @post.title %></center></h1>
		<p><center><%= @post.display_day_published %></center></p>
		<br>
		<br>
		<%= raw(@post.body) %>
>>>>>>> cfef13be2f99f4ad9f934a62d1a0d356a75139f9
	</div>
</div>	

app/views/welcome/index.html.erb
<% provide(:page_title, "Home") %>
<br/>

<!-- First Container ( Club Picture ) -->
<div class="container bg-1 text-center">
    <p id="text1">// Long Live Open Source :}</p>
    <div class="row">
        <div class="col-md-3"> 
            <!-- placeholder -->
        </div> 
        <div class="col-md-6">
            <a href="https://ccsu.campuslabs.com/engage/organization/App_Development_Club" class="protip" data-pt-title="Meetings take place every Monday 5 p.m. in Maria Sanford, Room 208!" data-pt-trigger="sticky" data-pt-gravity="bottom" data-pt-size="large" data-pt-animate="fadeInLeftBig" data-pt-target="a.protip"> 
<<<<<<< HEAD
            <%=image_tag("https://s3.us-east-2.amazonaws.com/app-dev-blog-site/club_photo.jpg", :class => "img-circle img-responsive") %> 
            </a>
        </div> 
        <div class="col-md-3"> 
            <div class="black-logo">
            <%=image_tag("https://s3.us-east-2.amazonaws.com/app-dev-blog-site/club_logo-b.png", class: "img-responsive") %> 
=======
            <img src="assets/club_photo.jpg" class="img-circle img-responsive" alt="Club Photo"></a>
        </div> 
        <div class="col-md-3"> 
            <div class="black-logo">
                <img src="assets/club_logo-b.png" class="img-responsive" alt="Club Logo">
>>>>>>> cfef13be2f99f4ad9f934a62d1a0d356a75139f9
            </div>   
        </div>  
    </div> 
</div>
<br/>
     
<!-- Second Container ( Mission )-->
<div class="container-fluid bg-2 text-center">  
    <h3>Our Mission</h3>
    <br/>
    <p>We will further our knowledge by focusing on a variety of applications that will allow students to broaden their skill sets and build their portfolios.</p>
    <br/>
    <a href="https://ccsu.campuslabs.com/engage/organization/App_Development_Club" class="btn btn-default btn-lg">Become a Member</a>  
</div>

<!-- Third Container ( 3x1 Grid ) -->
<div class="container-fluid bg-3 text-center">    
    <div class="row row-grid">
        <div class="col-sm-4">
            <h4 id="grid">Think</h4>
            <i class="fa fa-lightbulb-o fa-5x" aria-hidden="true"></i>
        </div>
        <div class="col-sm-4"> 
            <h4 id="grid">Collaborate</h4>
            <i class="fa fa-handshake-o fa-3x handshake" aria-hidden="true"></i>
        </div>
        <div class="col-sm-4"> 
            <h4 id="grid">Create</h4>
            <i class="fa fa-mobile fa-5x" aria-hidden="true"></i>
        </div>
    </div>
</div>

<!-- Footer ( Shout out to CCSU )-->
<footer class="container-fluid bg-4 text-center">
    <p>Brought to you by Central Connecticut State University 
<<<<<<< HEAD
    <%=image_tag("https://s3.us-east-2.amazonaws.com/app-dev-blog-site/ccsuLogo.svg", :size => "40x120") %> 
    </p>  
=======
    <img src="assets/ccsuLogo.svg" width="40px", height="120px"/></p>  
>>>>>>> cfef13be2f99f4ad9f934a62d1a0d356a75139f9
</footer>